String = Set{'Alice','Reading','Gaming','Cooking','Traveling'}
Person_min = 1
Person_max = 1
Person_name = Set{'Alice'}
# Định nghĩa các tập giá trị cho thuộc tính hobbies (Set(String))
Person_hobbies = Set{'Reading','Gaming', 'Cooking','Traveling'}