BinaryTree_min = 1
BinaryTree_max = 1
BinaryTree_size = Set{1,2,3,4,5,6,7,8,9,10}

Node_min = 10
Node_max = 10
Node_key = Set{1,2,3,4,5,6,7,8,9,10}

Root_min = 0
Root_max = 1

LeftChild_min = 0
LeftChild_max = 9

RightChild_min = 0
RightChild_max = 9

ParentNode_min = 0
ParentNode_max = 9

Node_Acyclic = active
Node_SearchLeft = active
Node_SearchRight = active
Node_ParentConsistent = active
BinaryTree_RootHasNoParent = active
Node_ReachableFromRoot = active
BinaryTree_TreeSize = active