String = Set{'HR','Engineering','Finance'}

Employee_min = 3
Employee_max = 5
Employee_id = Set{1,2,3,4,5}

Department_min = 1
Department_max = 2
Department_name = Set{'HR','Engineering','Finance'}

WorksIn_min = 1
WorksIn_max = 5

Department_NotEmpty = active
Department_MinStaff = active
Department_MaxStaff = active
Department_FirstEmployeeHasLowestId = active
