Integer_min = -1
Integer_max = 22

Process_min = 20
Process_max = 20

Mutex_min = 20
Mutex_max = 20

State_min = 2
State_max = 2

Hold_min = 0
Hold_max = 3

WaitQueue_min = 1
WaitQueue_max = 20
WaitQueue_queue_minSize = 1
WaitQueue_queue_maxSize = 20

StateTrace_min = 0
StateTrace_max = 2

MutexHierarchy_min = 0
MutexHierarchy_max = 20

State_MutualExclusion = active
WaitQueue_UniqueQueuePerMutexState = active
WaitQueue_NoDuplicateInQueue = active
WaitQueue_HoldNotWaiting = active
WaitQueue_DijkstraHierarchyRule = active
WaitQueue_StrictPriorityGrant = active
WaitQueue_EmptyQueueImpliesNoNewGrant = active
WaitQueue_ForceDeadlock = active
