Node_min = 10
Node_max = 20
Node_key = Set{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}

List_min = 1
List_max = 1
List_keySequence = Set{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20}
List_keySequence_minSize = 10
List_keySequence_maxSize = 20

Header_min = 1
Header_max = 1

Next_min = 0
Next_max = 20

Prev_min = 0
Prev_max = 20

List_HeaderNotNull = active
Node_NextPrevConsistency = active
List_SequenceSize = active
List_FirstKeyIsHeader = active
List_NoDuplicateKeys = active
List_AllKeysAreValid = active
List_SequenceMatchesPointers = active
