# String attribute domains and length constraints
Schema_name = Set{'S1', 'S2', 'S3', 'S4','S5'}

Entity_name = Set{'E1', 'E2', 'E3', 'E4', 'E5'}


Relship_name = Set{'R1', 'R2', 'R3', 'R4', 'R5'}
# Relship_name_length_min = 2
# Relship_name_length_max = 10

RelshipEnd_name = Set{'RE1', 'RE2', 'RE3', 'RE4', 'RE5'}
# RelshipEnd_name_length_min = 3
# RelshipEnd_name_length_max = 10

# Association cardinalities
entityAttributes_min = 1
entityAttributes_max = 10

entities_min = 1
entities_max = 10

relationshipEnds_min = 2
relationshipEnds_max = 10

relationships_min = 0
relationships_max = 10

typeOf_min = 0
typeOf_max = 10

# Class instance bounds
Schema_min = 0
Schema_max = 5

Entity_min = 0
Entity_max = 5

Relship_min = 0
Relship_max = 5

RelshipEnd_min = 0
RelshipEnd_max = 5

Attribute_min = 0
Attribute_max = 5

# Boolean attribute values
Attribute_isKey = Set{true, false}
