Customer_min = 0
Customer_max = 5

GoldCustomer_min = 0
GoldCustomer_max = 5

Portal_min = 0
Portal_max = 5

Sale_min = 0
Sale_max = 5

SaleLine_min = 0
SaleLine_max = 5

Product_min = 0
Product_max = 5

Real=Set{1.00,10.00,20.00}
# String attribute domains
Portal_url = Set{'http://a.com', 'http://b.com', 'http://c.com', 'http://d.com', 'http://e.com'}
Portal_name = Set{'P1', 'P2', 'P3', 'P4', 'P5'}
Customer_name = Set{'C1', 'C2', 'C3', 'C4', 'C5'}

# Attribute values
Sale_id = Set{1.00, 10.00, 20.00}
Sale_paid = Set{true, false}
Sale_amount = Set{1, 10, 20}
SaleLine_quantity = Set{1, 10, 20}
Product_price = Set{1, 10, 20}
Product_stock = Set{1, 10, 20}

# Association cardinalities
Purchases_min = 0
Purchases_max = 10

IncludedIn_min = 0
IncludedIn_max = 10

ProductSaleLines_min = 0
ProductSaleLines_max = 10

RegisteredIn_min = 0
RegisteredIn_max = 10
