Integer_min = 101
Integer_max = 124

Card_min = 6
Card_max = 14
Card_k1 = Set{101,102,103,104,105,106,107,108,109,110,111,112}
Card_k2 = Set{113,114,115,116,117,118,119,120,121,122,123,124}

Room_min = 8
Room_max = 8
Room_currentKeyId = Set{113,114,115,116,117,118,119,120,121,122,123,124}
Room_keyHistory = Set{101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124}
Room_keyHistory_minSize = 2
Room_keyHistory_maxSize = 4

Guest_min = 6
Guest_max = 11

Holds_min = 6
Holds_max = -1

Occupies_min = 6
Occupies_max = -1

Card_DiffKeys = active
Card_UniqueK2 = active
Room_KeyHistoryConsistent = active
Room_KeyHistoryMinSize = active
Room_NoRepeatedConsecutiveKeys = active
Guest_MustOccupy = active
Guest_MustHaveCard = active
Guest_ForceBadEntry = active
Guest_CardLinkedToRoom = active
Guest_NoIntervening = active
