Integer_min = 1
Integer_max = 8


Card_min = 4
Card_max = 8
Card_k1 = Set{1,2,3,4}
Card_k2 = Set{5,6,7,8}


Room_min = 4
Room_max = 4
Room_currentKeyId = Set{5,6,7,8}
Room_keyHistory_minSize = 2
Room_keyHistory_maxSize = 5


Guest_min = 4
Guest_max = 8


Holds_min = 4
Holds_max = -1


Occupies_min = 4
Occupies_max = -1


Card_DiffKeys = active
Card_UniqueK2 = active
Room_KeyHistoryConsistent = active
Room_KeyHistoryMinSize = active
Room_FirstKeyDiffersFromCurrent = active
Guest_MustOccupy = active
Guest_MustHaveCard = active
Guest_CardLinkedToRoom = active
Guest_CardOrderInHistory = active
Room_KeyHistoryNeverEmpty = active