Integer_min = 1
Integer_max = 24


Card_min = 12
Card_max = 24
Card_k1 = Set{1,2,3,4,5,6,7,8,9,10,11,12}
Card_k2 = Set{13,14,15,16,17,18,19,20,21,22,23,24}


Room_min = 12
Room_max = 12
Room_currentKeyId = Set{13,14,15,16,17,18,19,20,21,22,23,24}
Room_keyHistory = Set{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}
Room_keyHistory_minSize = 2
Room_keyHistory_maxSize = 13


Guest_min = 12
Guest_max = 24


Holds_min = 12
Holds_max = -1


Occupies_min = 12
Occupies_max = -1


Card_DiffKeys = active
Card_UniqueK2 = active
Room_KeyHistoryConsistent = active
Room_KeyHistoryMinSize = active
Room_FirstKeyDiffersFromCurrent = active
Guest_MustOccupy = active
Guest_MustHaveCard = active
Guest_CardLinkedToRoom = active
Guest_CardOrderInHistory = active
Room_KeyHistoryNeverEmpty = active
