Integer_min = 1
Integer_max = 16


Card_min = 8
Card_max = 16
Card_k1 = Set{1,2,3,4,5,6,7,8}
Card_k2 = Set{9,10,11,12,13,14,15,16}


Room_min = 8
Room_max = 8
Room_currentKeyId = Set{9,10,11,12,13,14,15,16}
Room_keyHistory = Set{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
Room_keyHistory_minSize = 2
Room_keyHistory_maxSize = 9


Guest_min = 8
Guest_max = 16


Holds_min = 8
Holds_max = -1


Occupies_min = 8
Occupies_max = -1


Card_DiffKeys = active
Card_UniqueK2 = active
Room_KeyHistoryConsistent = active
Room_KeyHistoryMinSize = active
Room_FirstKeyDiffersFromCurrent = active
Guest_MustOccupy = active
Guest_MustHaveCard = active
Guest_CardLinkedToRoom = active
Guest_CardOrderInHistory = active
Room_KeyHistoryNeverEmpty = active