# Class instance bounds
Library_min = 1
Library_max = 3

Book_min = 3
Book_max = 5

Author_min = 2
Author_max = 4

# Attribute values
String_min = 1
String_max = 20

# Book_tags_minSize = 1
Book_tags_maxSize = 3

# Association cardinalities
contains_min = 0
contains_max = 10

writtenBy_min = 1
writtenBy_max = 8

# Activate invariants
Book_tagsNotEmpty = active
Book_mustHaveAuthor = active