String = Set{'img001','img002','img003','img004','img005','img006','img007','img008','img009','img010','img011','img012','img013','img014','img015','img016','img017','img018','img019','img020','img021','img022','img023','img024','img025','img026','img027','img028','img029','img030','vid001','vid002','vid003','vid004','vid005','vid006','vid007','vid008','vid009','vid010','vid011','vid012','vid013','vid014','vid015','vid016','vid017','vid018','vid019','vid020','vid021','vid022','vid023','vid024','vid025','vid026','vid027','vid028','vid029','vid030'}

Asset_min = 58
Asset_max = 60
Asset_name = Set{'img001','img002','img003','img004','img005','img006','img007','img008','img009','img010','img011','img012','img013','img014','img015','img016','img017','img018','img019','img020','img021','img022','img023','img024','img025','img026','img027','img028','img029','img030','vid001','vid002','vid003','vid004','vid005','vid006','vid007','vid008','vid009','vid010','vid011','vid012','vid013','vid014','vid015','vid016','vid017','vid018','vid019','vid020','vid021','vid022','vid023','vid024','vid025','vid026','vid027','vid028','vid029','vid030'}

Catalog_min = 1
Catalog_max = 2
Catalog_catalogId = Set{'CAT1','CAT2'}
Catalog_playlist = Set{'img001','img002','vid001'}
Catalog_playlist_minSize = 1
Catalog_playlist_maxSize = 3

ShowingAssets_min = 1
ShowingAssets_max = -1

HiddenAssets_min = 0
HiddenAssets_max = -1

SelectedAssets_min = 0
SelectedAssets_max = -1

Catalog_DisjointStates = active
Catalog_SelectionMustBeShowing = active
Catalog_PlaylistOnlyShowingAssets = active
Catalog_PlaylistSequenceOperations = active