bitwidth = 32
Researcher_min = 20
Researcher_max = 40
String_min = 6
String_max = 20

Paper_min = 1
Paper_max = 5

Paper_wordCount = Set{1, 10, 20, 50, 100, 127}
Paper_studentPaper = Set{true, false}
Researcher_isStudent = Set{true, false}

Writes_min = 0
Writes_max = 15

Reviews_min = 0
Reviews_max = 120   