String = Set{'Alice','Bob',Reading','Gaming','Cooking','Traveling','Dancing'}
Person_min = 2
Person_max = 3
Integer_min = 1
Integer_max = 5
Person_name = Set{'Alice','Bob'}
# Định nghĩa các tập giá trị cho thuộc tính hobbies (Sequence(String))
Person_hobbies = Set{'Reading','Gaming','Cooking','Traveling','Dancing'}
# Giới hạn chiều dài của sequence hobbies
Person_hobbies_minSize = 3
Person_hobbies_maxSize = 5

# Activate invariants
Person_atLeastTwoHobbies = active
Person_hobbiesNotEmpty = active
Person_mustHaveReading = active