Integer_min = 1
Integer_max = 30

Container_min = 1
Container_max = 1

Container_items = Set{15,7,9,11}
Container_items_minSize = 5
Container_items_maxSize = 10

Container_atIndex1 = active
Container_atIndex2 = active

