Integer_min = 1
Integer_max = 5

# Chi can 1 Student de test
Student_min = 1
Student_max = 1

# Sequence scores: cho phep tu 1 den 3 phan tu
Student_scores_minSize = 2
Student_scores_maxSize = 3

# Bat invariant
Student_appendLast = active
