
String = Set{'TaskA','TaskB','Alice','Bob'}
Integer_min = 0
Integer_max = 3

Project_min = 1
Project_max = 1
Task_min = 1
Task_max = 3
User_min = 1
User_max = 1

Project_name = Set{'HomeTasks'}
Project_taskList_minSize = 3
Project_taskList_maxSize = 3

Task_title = Set{'Shopping','Coding','Exercise'}
Task_priority = Set{1,2,3}

User_name = Set{'Alice'}

Contains_min = 3
Contains_max = 3

Owns_min = 1
Owns_max = 1

# Activate / Deactivate invariants từ file USE

# Project_taskListNotEmpty = active
Project_noDuplicateTasks = active
Project_firstTaskIsLowestPriority = active
Project_lastTaskIsHighestPriority = active
# Project_lastTaskIsDone = active
# Project_subListInRange = active
# Project_compareTwoProjects = active

# User_assignedNotEmpty = active
# User_assignedOnlyOwnProject = active

# Task_priorityRange = active
# Task_statusValid = active
Task_uniquePriority = active

