
Schedule_min = 2
Schedule_max = 2

String = Set{'Meeting', 'Coding', 'Monday', 'Testing', 'Review','Tuesday','Wednesday','Thursday','Friday','Planning','Design'}
Schedule_date = Set{'Monday','Tuesday','Wednesday','Thursday','Friday'}
Schedule_tasks = Set{'Meeting','Coding','Testing', 'Review','Planning','Design'}
# Invariant activation
Schedule_MinTasks = active
Schedule_MaxTasks = active
Schedule_FirstIsMeeting = active
# Schedule_MeetingNotHave = active